on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: thepuzzlecell-windows
          path: build/windows/runner/Release
  build_web:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-artifact@v3
        with:
          name: thepuzzlecell-web
          path: build/web
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: thepuzzlecell-android
          path: build/app/outputs/apk/release
